name: triton_test
services:
  triton_server:
    build:
      context: /home/cc/serving-monitoring/serving/serving_onnx
      dockerfile: docker/Dockerfile.triton
    container_name: triton_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"  # for HTTP requests
      - "8001:8001"  # for GRPC requests
      - "8002:8002"  # for reporting metrics
    volumes:
      - ./models:/models  # Mount models directory

  streamlit:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: streamlit_service
    ports:
      - "8501:8501"  # Map host 8501 to container 8501
    depends_on:
      - triton_server
    environment:
      - TRITON_SERVER_URL=triton_server:8000
      - CHEST_XRAY_MODEL_NAME=chest_xray_detector

  jupyter:
    image: quay.io/jupyter/minimal-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - /home/cc/serving-monitoring/serving_onnx/workspace:/home/jovyan/work  # mount workspace
    command: >
      bash -c "python3 -m pip install bash_kernel tritonclient[all] && 
               python3 -m bash_kernel.install && start-notebook.sh"