name: "drift_preprocessor"
backend: "python"
max_batch_size: 1
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [3, 640, 640]
  }
]
output [
  {
    name: "preprocessed_images"
    data_type: TYPE_FP32
    dims: [3, 640, 640]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]