{
 "title": "Backend",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nv_inference_queue_duration_us", "legendFormat": "Queue Duration" }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nv_inference_request_duration_us",
     "legendFormat": "Request Duration"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nv_inference_request_failure", "legendFormat": "Request Duration" }
   ]
  },
  {
   "title": "Pending Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "nv_inference_pending_request_count",
     "legendFormat": "Pending Request Count"
    }
   ]
  },
  {
   "title": "Inference Exec Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "nv_inference_exec_count", "legendFormat": "Inference Exec Count" }
   ]
  },
  {
   "title": "Inference request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "nv_inference_request_duration_us",
     "legendFormat": "Inference request duration"
    }
   ]
  }
 ]
}